stages:
  - lint
  - deploy

variables:
  KUBE_NAMESPACE: "prod"
  KUBE_CONFIG: "${CI_PROJECT_DIR}/kubeconfig"

before_script:
  - echo "$KUBE_CONFIG_DATA" | base64 -d > $KUBE_CONFIG
  - export KUBECONFIG=$KUBE_CONFIG

lint:
  stage: lint
  image: "cytopia/yamllint"
  script:
    - yamllint -d "{extends: default, rules: {line-length: {max: 120}}}" .

k8s_deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl apply -f glpi-mariadb-k8s.yml -n $KUBE_NAMESPACE
  only:
    - prod
